<?php
    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner-top-block')->toHtml();
?>
<script>
    require([
        'jquery',
        'owlcarousel'
    ], function ($) {
        $(document).ready(function () {
            $(".owl-carousel").owlCarousel({
                loop:true,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                        nav:true
                    }
                }
            });
        });
    });
</script>