<div class="header">
    <p><span class="top"> TOP </span></p>
    <p class="brands"><i class="fas fa-align-right"></i><strong> BRANDS </strong><i class="fas fa-align-left"></i></p>
</div>
<div class="brands">
    <?php
    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('brands-block')->toHtml();
    ?>
</div>
<div class="product">
    <?php
    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('trending-block')->toHtml();
    ?>
</div>
<script>
    require([
        'jquery',
        'owlcarousel'
    ], function($) {
        $(document).ready(function() {
            $(".product-list").owlCarousel({
                loop: true,
                items: 4,
                responsiveClass: true,
                nav: true,
                dots: false
            });
        });
    });
</script>