<div class="top-container deal-content">
    <div class="row">
        <div class="col-8 image">
            <?php
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('img-hot-deal-block')->toHtml();
            ?>
        </div>
        <div class="col-4 content">
            <?php
            echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('content-hot-deal-block')->toHtml();
            ?>
            <div class="icon">
                <?php
                echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('icon-hot-deal-block')->toHtml();
                ?>
            </div>
            <div class="countdown">
                <?php
                echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('count-down-block')->toHtml();
                ?>
            </div>
        </div>
    </div>
</div>