<div class="header">
    <p><span class="year"> NEW </span></p>
    <p class="trend"><i class="fas fa-align-right"></i><strong> PRODUCT </strong><i class="fas fa-align-left"></i></p>
</div>
<div class="tab">
    <a href="#"><i class="fas fa-check"></i> WOMEN'S</a><a href="#"><i class="fas fa-times"></i> MAN'S</a><a href="#"><i class="fas fa-times"></i> BAG & SHOES</a><a href="#"><i class="fas fa-times"></i> JEWELRY</a><a href="#"><i class="fas fa-times"></i> ACCESSORIES</a>
</div>
<div class="product">
    <?php
    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('new-product-block')->toHtml();
    ?>
</div>
<script>
    require([
        'jquery',
        'owlcarousel'
    ], function($) {
        $(document).ready(function() {
            $(".product-list").owlCarousel({
                loop: true,
                items: 4,
                responsiveClass: true,
                nav: true,
                dots: false
            });
        });
    });
</script>