<div class="suggest-item row">
	<div class="special col-6">
		<p>SPECIAL ITEMS</p>
		<?php
	    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('speacial-items')->toHtml();
	    ?>
	</div>
	<div class="may-like col-6">
		<p>MAY YOU LIKE</p>
		<?php
	    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('may-you-like')->toHtml();
	    ?>
	</div>
</div>