<?php
    echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('trending-block')->toHtml();
?>
<!-- <script>
    require([
        'jquery',
        'owlcarousel'
    ], function ($) {
        $(document).ready(function () {
            $('.product-grid').owlCarousel({
                loop:true,
                nav:true,
                responsiveClass:true,
                itemClass: 'product-item'
            })
        });
    });
</script> -->